// Deliberately empty. An SPM C target with no sources fails to resolve, and the real
// contents of this target — `include/LumaCoreFFI.h` and `include/module.modulemap`
// — are generated by `ios/build-core.sh` and gitignored.
